version: '3.8'

services:
  # FastAPI Application
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=your-gemini-api-key-here
      - DEBUG=true
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

# Nginx removed

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
